Added an example for a simple calculator.
kiki7000/discord.py-components pull request #82
Opened 2021-06-04 23:12 UTC by Elektron-blip

# Added an example calculator.

## Why? 
Just cuz I felt like it. It is kinda useful for people new the lib too ig.

## PR TYPE
> Why did you open this PR (If it is other, please write a more detailed description.)
- [ ] New feature
- [ ] Fix bug
- [ ] Typo
- [x] Other

## Checks
- [x] Did you use the black formatter?
- [ ] Does this requires the users to change their code?
- [x] Did you test?
- [ ] Have you updated the docs?
- [x] Can you listen to our requests?
- [ ] Did you use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)

2021-06-04 23:54 UTC, kiki7000 commented on examples/intermediate/calculator.py
> +slash = SlashCommand(client, sync_commands=True)
Could you just use bot.command? All the other examples use that and this requires information about `discord-py-slash-command`

2021-06-04 23:54 UTC, kiki7000 commented on examples/intermediate/calculator.py
> +    e = discord.Embed(
Could you put this on `m.edit`? Not creating a variable

2021-06-05 06:09 UTC, Elektron-blip commented on examples/intermediate/calculator.py
> +slash = SlashCommand(client, sync_commands=True)
Resolved in https://github.com/kiki7000/discord.py-components/pull/82/commits/575498989f78646870de6286ae2b1507bc1c07c2

2021-06-05 06:09 UTC, Elektron-blip commented on examples/intermediate/calculator.py
> +    e = discord.Embed(
Resolved in https://github.com/kiki7000/discord.py-components/pull/82/commits/575498989f78646870de6286ae2b1507bc1c07c2

2021-06-05 06:11 UTC, Elektron-blip reviewed
It looks good to me.

2021-06-05 14:33 UTC, kiki7000 requested changes
Could you use Cog for this?

2021-06-05 15:37 UTC, Elektron-blip commented
> Could you use Cog for this?

I can use cogs for it but do you want it to be a cog on the same file or do you want it in multiple files?

2021-06-05 15:39 UTC, kiki7000 commented
Oh removing the command and replacing it with cog

2021-09-10 15:17 UTC, closed without merging