Add disable_components method to Message
kiki7000/discord.py-components pull request #94
Opened 2021-09-26 05:56 UTC by TheShubhendra

## PR TYPE
> Why did you open this PR (If it is other, please write a more detailed description.)
- [x] New feature

- [ ] Fix bug
- [ ] Typo
- [ ] Other

## Required
Just check if you followed the contents in the contributing file.

## Checks
- [ ] Is this a breaking change?

2021-09-26 10:48 UTC, kiki7000 requested changes
Could you also add disable_components to ActionRow?

2021-09-26 17:11 UTC, TheShubhendra commented
> Could you also add disable_components to ActionRow?

Done

2021-09-27 05:56 UTC, kiki7000 requested changes

2021-09-27 05:56 UTC, kiki7000 commented on discord_components/component.py
> +            map(disable, component) for component in self._components
that would cause an error
change to `map(disable, self._components)`

2021-09-27 05:56 UTC, kiki7000 commented on discord_components/component.py
> +
Return the disabled components

2021-09-27 05:56 UTC, kiki7000 commented on discord_components/dpy_overrides.py
> +    async def disable_components(self):
now you have disable_components in actionrow so just disabled_components = [row.disable_components for row in self.components]

2021-09-27 12:08 UTC, TheShubhendra commented
@kiki7000 Fixed all the issues, tested and squashed all the 3 three commits into one.

2021-10-07 13:18 UTC, kiki7000 requested changes

2021-10-07 13:18 UTC, kiki7000 commented on discord_components/component.py
> +
set self._components to disabled_row

2021-10-07 13:54 UTC, kiki7000 approved these changes

2021-10-07 13:54 UTC, merged